# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

# The changelog is managed by release-please
changelog:
  disable: true

builds:
  - binary: between
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"

nfpms:
  - package_name: between
    maintainer: 'staticaland'
    formats:
      - deb
      - rpm
      - archlinux

homebrew_casks:
  - name: between
    description: "A tool to extract content between two markers"
    homepage: "https://github.com/staticaland/between"
    repository:
      owner: staticaland
      name: between
    # The Casks directory is the default, but we can be explicit.
    directory: Casks
    # This will prevent conflicts with the old formula.
    conflicts:
      formula: "between"
    # To allow installation of unsigned binaries.
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/between"]
          end