# This file was generated by GoReleaser. DO NOT EDIT.
cask "between" do
  desc "A tool to extract content between two markers"
  homepage "https://github.com/staticaland/between"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "between"

  on_macos do
    on_intel do
      url "https://github.com/staticaland/between/releases/download/v0.4.0/between_0.4.0_darwin_amd64.tar.gz"
      sha256 "e6d41690d67b18407128faebea8c8da300071ec7cbf5693b8664d86ff46dacad"
    end
    on_arm do
      url "https://github.com/staticaland/between/releases/download/v0.4.0/between_0.4.0_darwin_arm64.tar.gz"
      sha256 "a20bfeb1a8711379926b0497a68738b95395bb19507ecebc63a95fab410f8cbb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/staticaland/between/releases/download/v0.4.0/between_0.4.0_linux_amd64.tar.gz"
      sha256 "a8b091aea38e47dc6eebdd4b5e452994dbb630149732ab10302d16e3a80874c3"
    end
    on_arm do
      url "https://github.com/staticaland/between/releases/download/v0.4.0/between_0.4.0_linux_arm64.tar.gz"
      sha256 "b22232a81059bc5786a6f164184baef9e558029d52aae321e441db2d0edd66cf"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/between"]
    end
  end

  # No zap stanza required
end
