# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Between < Formula
  desc "A tool to extract content between two markers"
  homepage "https://github.com/staticaland/between"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/staticaland/between/releases/download/v0.2.0/between_0.2.0_darwin_amd64.tar.gz"
      sha256 "f714b1a81088b47581f60d9fd55665f5b761e3836a48a2f86521327587e4b21b"

      def install
        bin.install "between"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/staticaland/between/releases/download/v0.2.0/between_0.2.0_darwin_arm64.tar.gz"
      sha256 "a35c7bc52c0a4cbb43cb6ea88993caac75c3625d21ae083c55e8f4149eafd595"

      def install
        bin.install "between"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/staticaland/between/releases/download/v0.2.0/between_0.2.0_linux_amd64.tar.gz"
      sha256 "86b1a05596624210b9056126ae11d909727a15a54c8d62058ceefa88d6327a47"
      def install
        bin.install "between"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/staticaland/between/releases/download/v0.2.0/between_0.2.0_linux_arm64.tar.gz"
      sha256 "099248531798ddae992a3baca360080e5d98dbeae624ee573d963f75a045b36c"
      def install
        bin.install "between"
      end
    end
  end
end
